import { GetFeatures } from "@/ServerActions/Feature/GetFeatures"
import FeaturesLayout from "../_Components/features-layout"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: "Features",
  description: "Generated by create next app",
};



export default async function FeaturesPage() {
  const features = await GetFeatures()
  return (
    <FeaturesLayout features={features}/>
  )
}
