import '@fortawesome/fontawesome-free/css/all.min.css';
import type { Metadata } from "next";
import { Exo } from "next/font/google";
import Providers from './_Components/Providers/Providers';
import "./globals.css";
import { useUserData } from '@/Context/UserData';

const exo = Exo({
  variable: "--font-exo",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={`${exo.className}   h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
