import { GetAdmins } from '@/ServerActions/Admin/GetAdmins';
import AdminsLayout from '../_Components/admins-layout';
import { Metadata } from "next"

export const metadata: Metadata = {
  title: "Admins",
  description: "Generated by create next app",
};


export default async function page() {
  const admins = await GetAdmins();
  return (
    <AdminsLayout
    initialAdmins={admins}
    />
  )
}
