
import { GetInstructors } from "@/ServerActions/Instructor/GetInstructor";
import InstructorsLayout from "../_Components/instructors-layout"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: "Instructors",
  description: "Generated by create next app",
};

export default async function InstructorsPage() {
  const instructors = await GetInstructors();
  return (
    <InstructorsLayout initialInstructors={instructors}/>
  )
}
