import { GetStudents } from "@/ServerActions/Student/GetStudents"
import StudentsLayout from "../_Components/students-layout"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: "Students",
  description: "Generated by create next app",
};

export default async function StudentsPage() {
  const students = await GetStudents();
  
  return (
    <StudentsLayout
      initialStudents={students}
    />
  )
}
