// app/enroll/page.tsx
import { GetCourses } from "@/ServerActions/Course/GetCourses";
import { GetProfile } from "@/ServerActions/Profile/GetProfile";
import { StudentRecord } from "@/Types/StudentTypes";
import { BookOpen } from "lucide-react";
import EnrollmentCard from "../_Components/enrollment-card";
import { Metadata } from "next"

export const metadata: Metadata = {
  title: "Course Enrollment",
  description: "Generated by create next app",
};

export default async function EnrollPage() {
  const [courses, student] = await Promise.all([
    // Ensure GetCourses uses fetch(url, { cache: 'no-store' }) internally
    GetCourses(),
    GetProfile() as Promise<StudentRecord | null>
  ]);

  if (!student) {
    return (
      <div className="flex flex-col items-center justify-center py-20">
        <BookOpen size={48} className="text-slate-300 mb-4" />
        <h2 className="text-xl font-bold text-slate-900">Student Profile Not Found</h2>
      </div>
    );
  }

  const userEnrollments = courses.filter(c => 
    c.students.some(s => s.student_id === student.student_id)
  );

  return (
    <div className="p-8 space-y-8 animate-in fade-in duration-500">
      <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
        <div className="rounded-2xl border border-indigo-100 bg-white p-6 shadow-sm">
          <p className="text-xs font-bold text-indigo-600 uppercase">Student</p>
          <h2 className="text-2xl font-black text-slate-900">{student.full_name.toUpperCase()}</h2>
        </div>
        <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <p className="text-xs font-bold text-slate-500 uppercase">Courses Enrolled</p>
          <p className="text-3xl font-black text-slate-900">{userEnrollments.length}</p>
        </div>
      </div>

      <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 xl:grid-cols-3">
        {courses.map((course) => (
          <EnrollmentCard 
            key={course.course_id} 
            course={course} 
            currentStudentId={student.student_id} 
          />
        ))}
      </div>
    </div>
  );
}