import { GetProfile } from "@/ServerActions/Profile/GetProfile";
import { GetTimetable } from "@/ServerActions/Timetable/GetTimetable";
import { InstructorRecord } from "@/Types/StudentTypes";
import { TimetableResponse } from "@/Types/TimetableTypes";
import InstructorTimetableLayout from "../_Components/timetable-layout";
import { Metadata } from "next"

export const metadata: Metadata = {
  title: "Timetable",
  description: "Generated by create next app",
};

export default async function TimetablePage() {
    let initialTimetable:TimetableResponse = [];
    let instructor:InstructorRecord;
    try {
        initialTimetable = await GetTimetable();
        instructor = await GetProfile();
    } catch {
        initialTimetable = []
        instructor = {} as InstructorRecord;
    }

    return <InstructorTimetableLayout initialTimetable={initialTimetable} instructor={instructor} />
}