// NO "use client"
import { GetCourses } from "@/ServerActions/Course/GetCourses"
import { GetProfile } from "@/ServerActions/Profile/GetProfile"
import { Course } from "@/Types/CourseTypes"
import { InstructorStateGrid } from "./_Components/instructor-state-grid"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: "Instructor Dashboard",
  description: "Generated by create next app",
};

export default async function InstructorDashboard() {
  const [profileData, allCourses] = await Promise.all([
    GetProfile(),
    GetCourses(0, 1000),
  ])
  console.log(profileData);

  const myCourses: Course[] = profileData
    ? allCourses.filter((c: Course) =>
      c.instructors.some((inst) => inst.instructor_id === profileData.instructor_id)
    )
    : []

  return <InstructorStateGrid profile={profileData} myCourses={myCourses} />
}