// app/admin/page.tsx  ← NO "use client"
import { GetCourses } from "@/ServerActions/Course/GetCourses"
import { GetFeatures } from "@/ServerActions/Feature/GetFeatures"
import { GetInstructors } from "@/ServerActions/Instructor/GetInstructor"
import { GetStudents } from "@/ServerActions/Student/GetStudents"
import { GetRooms } from "@/ServerActions/Room/GetRooms"
import { StatsGrid } from "./_Components/admin-state-grid"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default async function AdminDashboard() {
  const [coursesData, instructorsData, featuresData, studentsData, roomsData] =
    await Promise.all([
      GetCourses(0, 1000),
      GetInstructors(0, 1000),
      GetFeatures(0, 1000),
      GetStudents(0, 1000),
      GetRooms(0, 1000),
    ])

  const stats = {
    features: featuresData.length,
    rooms: roomsData.length,
    instructors: instructorsData.length,
    courses: coursesData.length,
    students: studentsData.length,
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-1">
        <h1 className="text-2xl font-bold tracking-tight text-foreground md:text-3xl">
          Welcome back, Admin
        </h1>
        <p className="text-muted-foreground">
          Here&apos;s what&apos;s happening with your learning platform today.
        </p>
      </div>

      <StatsGrid stats={stats} />
    </div>
  )
}