import { GetTimetable } from "@/ServerActions/Timetable/GetTimetable"
import { TimetableResponse } from "@/Types/TimetableTypes"
import { StudentRecord } from "@/Types/StudentTypes";
import { GetProfile } from "@/ServerActions/Profile/GetProfile";
import StudentTimetableLayout from "../_Components/timetable-layout";
import { Metadata } from "next"

export const metadata: Metadata = {
  title: "Timetable",
  description: "Generated by create next app",
};

export default async function TimetablePage() {
    let initialTimetable:TimetableResponse = [];
    let student:StudentRecord;
    try {
        initialTimetable = await GetTimetable();
        student = await GetProfile();
    } catch {
        initialTimetable = []
        student = {} as StudentRecord;
    }

    return <StudentTimetableLayout initialTimetable={initialTimetable} student={student} />
}